from LL import LinkedList
# #print(ll)
# #print(ll.head.value)
#ll= LinkedList(0)
# ll.append(1)
# #print("-------")
# #ll.print()
# #ll.popFront()
# #print("------- first pop")
# #ll.print()
# #print("------- adding elements")
# # ll.append(2)
# # ll.append(3)
# # ll.append(4)
# # ll.append(5)
# # ll.append(6)
# #ll.print()
# #print("------- second pop")
# #ll.popFront()
# ll.print()
# ll.pop()
# print("------- first pop")
# #ll.print()
# ll.pop()
# # print(ll.pop())
# ll.append(1)
# ll.prepend(0)
# ll.print()
# ll.popFirst()
# ll.popFirst()
# print(ll.popFirst())
# ll.append(0)
# ll.append(2)
# ll.append(3)
# ll.append(4)
# ll.append(5)
# ll.append(6)
# print("----Set Method Test")
# #print(ll.get(5).value)
# print("previous value :"+str(ll.getValue(3).value))
# ll.set(3,-1)
# print("after set  value :"+str(ll.getValue(3).value))
#
# print("----Insert Method Test")
#
# print("before insert value :"+str(ll.getValue(3).value))
# ll.insert(3,100)
# print("after set  value :"+str(ll.getValue(3).value))
#
#
# print("----remove Method Test")
#
# print("before remove value :")
# ll.print()
# ll.remove(3)
# print("after set  value :"+str(ll.getValue(3).value))
# ll.print()

ll= LinkedList(1)
ll.append(2)
ll.append(3)
ll.append(4)
ll.append(5)
ll.append(6)
ll.reverse()
ll.print()